### PR TITLE
Fix Site Create command with Self SSL on Mac via Homebrew.

### LINKED ISSUE #312: Self SSL is not working on mac via Homebrew
### Steps to Reproduce
- Install EasyEngine on Mac. `brew install easyengine`
- Create an HTML site with Self SSL. `ee site create example.test --type=html --ssl=self`
- Access the Website with HTTPS protocol URL. `https://example.test`
- Observe the response.

### System Info
```
+-------------------+-----------------------------------------------------------------------------------------------------------------------+
| OS                | Darwin 18.6.0 Darwin Kernel Version 18.6.0: Thu Apr 25 23:16:27 PDT 2019; root:xnu-4903.261.4~2/RELEASE_X86_64 x86_64 |
| Shell             | /bin/zsh                                                                                                              |
| PHP binary        | /usr/local/Cellar/php/7.3.5/bin/php                                                                                   |
| PHP version       | 7.3.5                                                                                                                 |
| php.ini used      | /usr/local/etc/php/7.3/php.ini                                                                                        |
| EE root dir       | phar://ee.phar                                                                                                        |
| EE vendor dir     | phar://ee.phar/vendor                                                                                                 |
| EE phar path      | /Users/udit.desai                                                                                                     |
| EE packages dir   |                                                                                                                       |
| EE global config  | /Users/udit.desai/easyengine/config/config.yml                                                                        |
| EE project config |                                                                                                                       |
| EE version        | 4.0.14                                                                                                                |
+-------------------+-----------------------------------------------------------------------------------------------------------------------+
```

### Observed Behavior

- The site was not accessible on the browser on HTTPS protocol.

Screen Shot 2019-05-27 at 00 31 41

- However, the site was accessible on the HTTP protocol.

Screen Shot 2019-05-27 at 00 39 07

### Debug log of the site create command
```
~|⇒ ee site create example.test --type=html --ssl=self --debug
Debug: ----------------------- (0.023s)
Debug: COMMAND: cd /Users/udit.desai/easyengine/services && docker ps -q --no-trunc | grep $(docker-compose ps -q global-nginx-proxy) (0.024s)
Debug: STDOUT: 4050a19b9c52d1ad4a0bc8c88d2de09607447104f4fc0dd969c687b34f6c1828
 (0.527s)
Debug: RETURN CODE: 0 (0.527s)
Debug: ----------------------- (0.527s)
Debug: ----------------------- (0.527s)
Debug: COMMAND: docker ps > /dev/null (0.528s)
Debug: RETURN CODE: 0 (0.582s)
Debug: ----------------------- (0.583s)
Debug: ----------------------- (0.583s)
Debug: COMMAND: command -v docker-compose > /dev/null (0.583s)
Debug: RETURN CODE: 0 (0.588s)
Debug: ----------------------- (0.588s)
Debug (bootstrap): Using default global config: /Users/udit.desai/easyengine/config/config.yml (0.591s)
Debug (bootstrap): No project config found (0.591s)
Debug (bootstrap): argv: /usr/local/bin/ee site create example.test --type=html --ssl=self --debug (0.591s)
Debug (bootstrap): Running command: site (0.591s)
Debug (bootstrap): Running command: site create (0.593s)
Debug: COMMAND: which docker (0.604s)
Debug: RETURN CODE: 0 (0.605s)
Debug: ----------------------- (0.605s)
Debug: COMMAND: docker inspect -f '{{.State.Running}}' 4050a19b9c52d1ad4a0bc8c88d2de09607447104f4fc0dd969c687b34f6c1828 (0.605s)
Debug: STDOUT: true
 (0.654s)
Debug: RETURN CODE: 0 (0.654s)
Debug: ----------------------- (0.654s)
Debug: ----------------------- (0.655s)
Debug: COMMAND: docker inspect --format '{{ (index (index .NetworkSettings.Ports "80/tcp") 0).HostPort }}' 4050a19b9c52d1ad4a0bc8c88d2de09607447104f4fc0dd969c687b34f6c1828 (0.655s)
Debug: STDOUT: 80
 (0.71s)
Debug: RETURN CODE: 0 (0.71s)
Debug: ----------------------- (0.71s)
Debug: ----------------------- (0.71s)
Debug: COMMAND: docker inspect --format '{{ (index (index .NetworkSettings.Ports "443/tcp") 0).HostPort }}' 4050a19b9c52d1ad4a0bc8c88d2de09607447104f4fc0dd969c687b34f6c1828 (0.71s)
Debug: STDOUT: 443
 (0.763s)
Debug: RETURN CODE: 0 (0.764s)
Debug: ----------------------- (0.764s)
Configuring project.
Debug: ----------------------- (0.764s)
Debug: COMMAND: whoami (0.764s)
Debug: STDOUT: udit.desai
 (0.771s)
Debug: RETURN CODE: 0 (0.771s)
Debug: ----------------------- (0.771s)
Creating site example.test.
Copying configuration files.
Starting site's services.
Debug: ----------------------- (0.777s)
Debug: COMMAND: docker-compose up -d nginx (0.777s)
Debug: STDERR: Creating network "example.test" with the default driver
Creating exampletest_nginx_1 ... done
 (2.409s)
Debug: RETURN CODE: 0 (2.409s)
Debug: ----------------------- (2.409s)
Debug: ----------------------- (2.41s)
Debug: COMMAND: docker-compose exec --user="root" nginx bash -c "chown -R www-data: /var/www/htdocs" (2.41s)
Debug: RETURN CODE: 0 (3.058s)
Debug: ----------------------- (3.058s)
Success: Configuration files copied.
Debug: ----------------------- (3.058s)
Debug: COMMAND: command -v brew (3.058s)
Debug: STDOUT: /usr/local/bin/brew
 (3.063s)
Debug: RETURN CODE: 0 (3.063s)
Debug: ----------------------- (3.063s)
Checking and verifying site-up status. This may take some time.
Debug: example.test status httpcode: 0 (3.087s)
.Debug:example.test status httpcode: 200 (5.099s)

Debug: ----------------------- (5.104s)
Debug: COMMAND: docker exec 4050a19b9c52d1ad4a0bc8c88d2de09607447104f4fc0dd969c687b34f6c1828 sh -c "nginx -t" (5.104s)
Debug: STDERR: nginx: the configuration file /etc/nginx/nginx.conf syntax is ok
nginx: configuration file /etc/nginx/nginx.conf test is successful
 (5.305s)
Debug: RETURN CODE: 0 (5.306s)
Debug: ----------------------- (5.306s)
Debug: ----------------------- (5.306s)
Debug: COMMAND: docker exec 4050a19b9c52d1ad4a0bc8c88d2de09607447104f4fc0dd969c687b34f6c1828 sh -c "/app/docker-entrypoint.sh /usr/local/bin/docker-gen /app/nginx.tmpl /etc/nginx/conf.d/default.conf; /usr/sbin/nginx -s reload" (5.306s)
Debug: STDOUT: Custom dhparam.pem file found, generation skipped
 (5.649s)
Debug: STDERR: 2019/05/26 07:15:01 Contents of /etc/nginx/conf.d/default.conf did not change. Skipping notification ''
 (5.649s)
Debug: RETURN CODE: 0 (5.649s)
Debug: ----------------------- (5.65s)
Debug: ----------------------- (5.65s)
Debug: COMMAND: docker exec 4050a19b9c52d1ad4a0bc8c88d2de09607447104f4fc0dd969c687b34f6c1828 sh -c "nginx -t" (5.65s)
Debug: STDERR: nginx: the configuration file /etc/nginx/nginx.conf syntax is ok
nginx: configuration file /etc/nginx/nginx.conf test is successful
 (5.84s)
Debug: RETURN CODE: 0 (5.84s)
Debug: ----------------------- (5.84s)
Debug: ----------------------- (5.84s)
Debug: COMMAND: docker exec 4050a19b9c52d1ad4a0bc8c88d2de09607447104f4fc0dd969c687b34f6c1828 sh -c "/app/docker-entrypoint.sh /usr/local/bin/docker-gen /app/nginx.tmpl /etc/nginx/conf.d/default.conf; /usr/sbin/nginx -s reload" (5.84s)
Debug: STDOUT: Custom dhparam.pem file found, generation skipped
 (6.173s)
Debug: STDERR: 2019/05/26 07:15:02 Generated '/etc/nginx/conf.d/default.conf' from 2 containers
 (6.174s)
Debug: RETURN CODE: 0 (6.174s)
Debug: ----------------------- (6.174s)
Debug: ----------------------- (6.198s)
Debug: COMMAND: docker exec 4050a19b9c52d1ad4a0bc8c88d2de09607447104f4fc0dd969c687b34f6c1828 sh -c "nginx -t" (6.198s)
Debug: STDERR: nginx: the configuration file /etc/nginx/nginx.conf syntax is ok
nginx: configuration file /etc/nginx/nginx.conf test is successful
 (6.406s)
Debug: RETURN CODE: 0 (6.406s)
Debug: ----------------------- (6.406s)
Debug: ----------------------- (6.407s)
Debug: COMMAND: docker exec 4050a19b9c52d1ad4a0bc8c88d2de09607447104f4fc0dd969c687b34f6c1828 sh -c "/app/docker-entrypoint.sh /usr/local/bin/docker-gen /app/nginx.tmpl /etc/nginx/conf.d/default.conf; /usr/sbin/nginx -s reload" (6.407s)
Debug: STDOUT: Custom dhparam.pem file found, generation skipped
 (6.745s)
Debug: STDERR: 2019/05/26 07:15:02 Generated '/etc/nginx/conf.d/default.conf' from 2 containers
 (6.745s)
Debug: RETURN CODE: 0 (6.745s)
Debug: ----------------------- (6.745s)
Debug: Starting SSL procedure (6.745s)
Debug: Starting self signed cert generation (6.746s)
Debug: ----------------------- (6.747s)
Debug: COMMAND: openssl req -new -sha256 -nodes -passout pass:bt9OZTXLFJmA -out /Users/udit.desai/easyengine/services/nginx-proxy/self-signed-certs/example.test.csr -newkey rsa:2048 -keyout /Users/udit.desai/easyengine/services/nginx-proxy/self-signed-certs/example.test.key -config /Users/udit.desai/easyengine/services/nginx-proxy/self-signed-certs/example.test.conf (6.747s)
Debug: STDERR: Generating a RSA private key
................................................................................................................................................................................................+++++
...+++++
writing new private key to '/Users/udit.desai/easyengine/services/nginx-proxy/self-signed-certs/example.test.key'
-----
 (7.022s)
Debug: RETURN CODE: 0 (7.022s)
Debug: ----------------------- (7.022s)
Debug: ----------------------- (7.022s)
Debug: COMMAND: openssl x509 -req -in /Users/udit.desai/easyengine/services/nginx-proxy/self-signed-certs/example.test.csr -CA /Users/udit.desai/easyengine/services/nginx-proxy/self-signed-certs/rootCA.pem -CAkey /Users/udit.desai/easyengine/services/nginx-proxy/self-signed-certs/rootCA.key -CAcreateserial -passin pass:bt9OZTXLFJmA -out /Users/udit.desai/easyengine/services/nginx-proxy/self-signed-certs/example.test.crt -days 1024 -sha256 -extfile /Users/udit.desai/easyengine/services/nginx-proxy/self-signed-certs/example.test.v3.ext (7.022s)
Debug: STDERR: Signature ok
subject=/C=IN/ST=MH/L=Pune/O=EasyEngine/OU=EasyEngine/emailAddress=support@easyengine.io/CN=example.test
Getting CA Private Key
/Users/udit.srl: Permission denied
4675118700:error:06067099:digital envelope routines:EVP_PKEY_copy_parameters:different parameters:p_lib.c:137:
4675118700:error:02001002:system library:fopen:No such file or directory:bss_file.c:413:fopen('/Users/udit.srl','r')
4675118700:error:20074002:BIO routines:FILE_CTRL:system lib:bss_file.c:415:
4675118700:error:0200100D:system library:fopen:Permission denied:bss_file.c:413:fopen('/Users/udit.srl','w')
4675118700:error:20074002:BIO routines:FILE_CTRL:system lib:bss_file.c:415:
 (7.054s)
Debug: RETURN CODE: 1 (7.054s)
Debug: ----------------------- (7.054s)
Starting site's services.
Debug: ----------------------- (7.056s)
Debug: COMMAND: docker-compose up -d (7.056s)
Recreating exampletest_nginx_1 ... done
 (9.842s)
Debug: RETURN CODE: 0 (9.843s)
Debug: ----------------------- (9.843s)
Debug: ----------------------- (9.843s)
Debug: COMMAND: docker exec 4050a19b9c52d1ad4a0bc8c88d2de09607447104f4fc0dd969c687b34f6c1828 sh -c "nginx -t" (9.843s)
Debug: STDERR: nginx: [emerg] PEM_read_bio_X509_AUX("/etc/nginx/certs/example.test.crt") failed (SSL: error:0906D06C:PEM routines:PEM_read_bio:no start line:Expecting: TRUSTED CERTIFICATE)
nginx: configuration file /etc/nginx/nginx.conf test failed
 (10.072s)
Debug: RETURN CODE: 1 (10.072s)
Debug: ----------------------- (10.072s)
Debug: ----------------------- (10.072s)
Debug: COMMAND: docker exec 4050a19b9c52d1ad4a0bc8c88d2de09607447104f4fc0dd969c687b34f6c1828 sh -c "/app/docker-entrypoint.sh /usr/local/bin/docker-gen /app/nginx.tmpl /etc/nginx/conf.d/default.conf; /usr/sbin/nginx -s reload" (10.072s)
Debug: STDOUT: Custom dhparam.pem file found, generation skipped
 (10.385s)
Debug: STDERR: 2019/05/26 07:15:06 Generated '/etc/nginx/conf.d/default.conf' from 2 containers
nginx: [emerg] PEM_read_bio_X509_AUX("/etc/nginx/certs/example.test.crt") failed (SSL: error:0906D06C:PEM routines:PEM_read_bio:no start line:Expecting: TRUSTED CERTIFICATE)
 (10.385s)
Debug: RETURN CODE: 1 (10.385s)
Debug: ----------------------- (10.385s)
+--------------+----------------------------------------------------------+
| Site         | https://example.test                                     |
+--------------+----------------------------------------------------------+
| Site Root    | /Users/udit.desai/easyengine/sites/example.test          |
+--------------+----------------------------------------------------------+
| SSL          | Enabled                                                  |
+--------------+----------------------------------------------------------+
| SSL Wildcard | Yes                                                      |
+--------------+----------------------------------------------------------+
Site entry created.
```

**Notice the errors towards the end of the debug log.**

```
Debug: STDERR: Signature ok
subject=/C=IN/ST=MH/L=Pune/O=EasyEngine/OU=EasyEngine/emailAddress=support@easyengine.io/CN=example.test
Getting CA Private Key
/Users/udit.srl: Permission denied
4675118700:error:06067099:digital envelope routines:EVP_PKEY_copy_parameters:different parameters:p_lib.c:137:
4675118700:error:02001002:system library:fopen:No such file or directory:bss_file.c:413:fopen('/Users/udit.srl','r')
4675118700:error:20074002:BIO routines:FILE_CTRL:system lib:bss_file.c:415:
4675118700:error:0200100D:system library:fopen:Permission denied:bss_file.c:413:fopen('/Users/udit.srl','w')
4675118700:error:20074002:BIO routines:FILE_CTRL:system lib:bss_file.c:415:
 (7.054s)
Debug: RETURN CODE: 1 (7.054s)
```

```
Debug: STDERR: nginx: [emerg] PEM_read_bio_X509_AUX("/etc/nginx/certs/example.test.crt") failed (SSL: error:0906D06C:PEM routines:PEM_read_bio:no start line:Expecting: TRUSTED CERTIFICATE)
nginx: configuration file /etc/nginx/nginx.conf test failed
 (10.072s)
Debug: RETURN CODE: 1 (10.072s)
```

```
Debug: STDERR: 2019/05/26 07:15:06 Generated '/etc/nginx/conf.d/default.conf' from 2 containers
nginx: [emerg] PEM_read_bio_X509_AUX("/etc/nginx/certs/example.test.crt") failed (SSL: error:0906D06C:PEM routines:PEM_read_bio:no start line:Expecting: TRUSTED CERTIFICATE)
 (10.385s)
Debug: RETURN CODE: 1 (10.385s)
```

### Expected Behavior
1. Either above errors should be reported on the CLI
2. Or these errors should not have occurred in the first place. There has to be a way to generate the Self SSL for the website gracefully.

### PR DESCRIPTION
**Pull request by desaiuditd**
Fixes #312

### CODE REVIEW

**Comment by desaiuditd** [comment]
Ref: https://github.com/facebook/flipper/issues/101#issuecomment-406563584

Ref: https://github.com/Accenture/adop-docker-compose/pull/75/files

**Comment by dhsathiya** [comment]
Step taken :

**Comment by dhsathiya** [comment]
Steps taken : 
1. Cleaned the system. [Removing all docker containers and sites]
2. Cloned EasyEngine repository
3. `$ composer install`
4. `$ ./bin/ee site create test1.test --type=html --ssl=self --debug`
The site has been created successfully without any issues.
---
curl : 
```
╰─➤  curl -XGET -IL http://test1.test
HTTP/1.1 301 Moved Permanently
Server: nginx
Date: Tue, 28 May 2019 11:55:29 GMT
Content-Type: text/html
Content-Length: 178
Connection: keep-alive
Location: https://test1.test/
X-Powered-By: EasyEngine v4.0.14

HTTP/2 200 
server: nginx
date: Tue, 28 May 2019 11:55:34 GMT
content-type: text/html
content-length: 188
last-modified: Tue, 28 May 2019 11:18:36 GMT
vary: Accept-Encoding
etag: "5ced190c-bc"
accept-ranges: bytes
x-powered-by: EasyEngine v4.0.14
```
Debug log : 
https://pastebin.com/FbxNUyMh

**Comment by desaiuditd** [comment]
@dhsathiya What do you suggest? That it's not a bug?

Did you check my debug log that I posted in #312?

According to that, it seems like, the default path for the serial filename seems to be taken wrongly.

OpenSSL documentation says that default path is the current directory. (Ref: https://www.openssl.org/docs/man1.0.2/apps/x509.html) But clearly, here, it's only taking partial path. Check below errors from the log:

```
fopen:No such file or directory:bss_file.c:413:fopen('/Users/udit.srl','r')
...
fopen:Permission denied:bss_file.c:413:fopen('/Users/udit.srl','w')
```

So instead of depending on the default path, I chose to provide a dedicated path for the serial file. That's my fix.

**Comment by mrrobot47** [comment]
@desaiuditd thanks for the solution and raising the issue. 

I am closing this PR in favor of #314. 

http://users.skynet.be/pascalbotte/art/server-cert.htm
>The first time you use your CA to sign a certificate you can use the -CAcreateserial option. This option will create a file (ca.srl) containing a serial number. You are probably going to create more certificate, and the next time you will have to do that use the -CAserial option (and no more -CAcreateserial) followed with the name of the file containing your serial number. This file will be incremented each time you sign a new certificate. This serial number will be readable using a browser (once the certificate is imported to a pkcs12 format). And we can have an idea of the number of certificate created by a CA.

The reason being that #314 has implemented logic as stated above, creating the serial file for the rootCA when being used first time, and from second time onwards passing it with full path to -CAserial option. With this, the serial number maintains and increments after each cert is signed. Whereas in your solution you were creating serial files individially each time for every site, which might work, but not sure if it is technically a correct solution.

Test the PR #314 and let me know if it works properly for you.

**Comment by desaiuditd** [comment]
> The reason being that #314 has implemented logic as stated above, creating the serial file for the rootCA when being used first time, and from second time onwards passing it with full path to -CAserial option. With this, the serial number maintains and increments after each cert is signed. Whereas in your solution you were creating serial files individially each time for every site, which might work, but not sure if it is technically a correct solution.
> 
> Test the PR #314 and let me know if it works properly for you.

Ah. Makes sense. All good. Thanks. 🙂

**Pull request closed without merging**
