### PR TITLE
Add travis tests and integration

### PR DESCRIPTION
**Pull request by mrrobot47**
Closes https://github.com/EasyEngine/easyengine/issues/1116

### CODE REVIEW

**Comment by mbtamuli** [comment]
@mrrobot47 Did you verify if the tests will run for PRs as well?

**Comment by mrrobot47** [comment]
@mbtamuli Yes. Even this is a PR only, and all the tests have run properly and the `.travis.yml` as well as the tests committed in this PR have been run properly.

**Comment by mbtamuli** [comment]
@mrrobot47 Please run the commands in `debug` mode. If it is possible to set it in global settings, please update that.

**Comment by mrrobot47** [comment]
@mbtamuli I am not running in `debug` mode bu default because the behat tests compares the output in many tests. Hence, adding debug by default would change the console output and possibly lead to faliure of test.
To take care of it, in the `after_script` portion of travis, I am displaying the log file. Thus, we will have all the debug lig displayed at the end and know if there were any issues if a certain test failed.

**Comment by mbtamuli** [comment]
> To take care of it, in the after_script portion of travis, I am displaying the log file.

Oh. This is good. I missed this part.

**Pull request merged**
